local core = require("ruboterm256.palette.std.core")
local uno = require("ruboterm256.palette.std.uno")
local duo = require("ruboterm256.palette.std.duo")
local sty = require("ruboterm256.palette.std.style")

local M = {
	Normal = { fg = uno.uno_4, bg = core.Empty, style = sty.Empty },
	bold = { fg = core.Empty, bg = core.Empty, style = sty.bold },
	ColorColumn = { fg = core.Empty, bg = core.syntax_cursor_line, style = sty.Empty },
	Conceal = { fg = core.Empty, bg = core.Empty, style = sty.Empty },
	Cursor = { fg = core.syntax_bg, bg = core.syntax_accent, style = sty.Empty },
	CursorIM = { fg = core.Empty, bg = core.Empty, style = sty.Empty },
	CursorColumn = { fg = core.Empty, bg = core.syntax_cursor_line, style = sty.Empty },
	CursorLine = { fg = core.Empty, bg = core.syntax_cursor_line, style = sty.Empty },
	Directory = { fg = uno.uno_1, bg = core.Empty, style = sty.Empty },
	ErrorMsg = { fg = core.syntax_color_removed, bg = core.syntax_bg, style = sty.none },
	VertSplit = { fg = core.syntax_fold_bg, bg = core.Empty, style = sty.none },
	Folded = { fg = core.syntax_bg, bg = core.syntax_fold_bg, style = sty.Empty },
	FoldColumn = { fg = uno.uno_3, bg = core.syntax_cursor_line, style = sty.Empty },
	IncSearch = { fg = core.syntax_bg, bg = uno.uno_4, style = sty.Empty },
	LineNr = { fg = core.syntax_fold_bg, bg = core.Empty, style = sty.Empty },
	CursorLineNr = { fg = uno.uno_2, bg = core.Empty, style = sty.none },
	MatchParen = { fg = core.syntax_bg, bg = core.syntax_accent, style = sty.Empty },
	Italic = { fg = core.Empty, bg = core.Empty, style = sty.italic },
	ModeMsg = { fg = core.syntax_color_added, bg = core.Empty, style = sty.Empty },
	MoreMsg = { fg = core.syntax_fg, bg = core.Empty, style = sty.Empty },
	NonText = { fg = uno.uno_4, bg = core.Empty, style = sty.Empty },
	PMenu = { fg = core.Empty, bg = core.syntax_selection, style = sty.Empty },
	PMenuSel = { fg = core.Empty, bg = core.syntax_bg, style = sty.Empty },
	PMenuSbar = { fg = core.Empty, bg = core.syntax_bg, style = sty.Empty },
	PMenuThumb = { fg = core.Empty, bg = uno.uno_1, style = sty.Empty },
	Question = { fg = core.syntax_accent, bg = core.Empty, style = sty.Empty },
	Search = { fg = core.syntax_bg, bg = uno.uno_4, style = sty.Empty },
	SpecialKey = { fg = core.syntax_fold_bg, bg = core.Empty, style = sty.Empty },
	StatusLine = { fg = core.syntax_fg, bg = core.syntax_cursor_line, style = sty.none },
	StatusLineNC = { fg = uno.uno_4, bg = core.Empty, style = sty.Empty },
	TabLine = { fg = uno.uno_4, bg = core.Empty, style = sty.Empty },
	TabLineFill = { fg = core.Empty, bg = core.Empty, style = sty.none },
	TabLineSel = { fg = core.syntax_fg, bg = core.Empty, style = sty.Empty },
	Title = { fg = duo.duo_2, bg = core.Empty, style = sty.bold },
	Visual = { fg = core.Empty, bg = core.syntax_selection, style = sty.Empty },
	VisualNOS = { fg = core.Empty, bg = core.syntax_selection, style = sty.Empty },
	WarningMsg = { fg = core.syntax_accent, bg = core.Empty, style = sty.Empty },
	TooLong = { fg = core.syntax_accent, bg = core.Empty, style = sty.Empty },
	WildMenu = { fg = core.syntax_fg, bg = uno.uno_4, style = sty.Empty },
	SignColumn = { fg = core.Empty, bg = uno.uno_4, style = sty.Empty },
	Special = { fg = duo.duo_2, bg = core.Empty, style = sty.Empty },
}

return M
